version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    restart: always 
    volumes:
      - ./fake_data/:/usr/share/elasticsearch/data:rw
    user: "1000:0"
    environment:
      - xpack.security.enabled=false
      - node.name=elasticsearch
      - discovery.type=single-node
      - network.host=0.0.0.0
      # - ELASTIC_PASSWORD=Welcome123
    ports:
      - 9200:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/pipeline/
    ports:
      - 5044:5044
      - 8080:8080  
    command: sh -c  "bin/logstash-plugin install logstash-input-websocket && bin/logstash -f /usr/share/logstash/pipeline/logstash.conf"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  logstash:
  elastic_data:
    driver: local
    

